name: 'Setup Node'
description: 'Setup the NodeJS environment'

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - run: npm ci
      shell: bash
