name: Release
on:
  push:
    branches:
      - master

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
      - run: npm ci
      - run: |
          git config user.name "Laurent Dezitter"
          git config user.name "laurent.dezitter@gmail.com"
      - run: npm run version
      - run: git push --atomic --follow-tags origin master
